// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "ce377f3e-92c3-4d5d-affb-3cdf69513aaa";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onRelayDownChange();
void onRelayUpChange();

bool relay_down;
bool relay_up;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(relay_down, READWRITE, ON_CHANGE, onRelayDownChange);
  ArduinoCloud.addProperty(relay_up, READWRITE, ON_CHANGE, onRelayUpChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
